name: pole
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get_it: ^8.0.3
  go_router: ^14.8.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  rx_shared_preferences: ^4.0.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  dio: ^5.6.0
  pretty_dio_logger: ^1.4.0
  flutter_svg: ^2.0.17
  flutter_bloc: ^9.0.0
  dartx: ^1.2.0
  bloc_presentation: ^1.1.0
  infinite_scroll_pagination: ^5.0.0
  fast_immutable_collections: ^11.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.14.2
  test: ^1.25.8

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Eithai-Gothic
      fonts:
        - asset: assets/fonts/KOT-Eitai-Gothic-Bold.ttf

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 23
  macos:
    generate: true
    image_path: "assets/images/app_icon.png"
